#!/usr/bin/env python
# -*- coding: utf-8 -*-

PARTICIPLE  = 1024
IMPERATIVE  =  512
INDICATIVE  =  256
PASSIVE     =   16
ING         =    8
FUTURE      =    4
PAST        =    2
PERFECT     =    1

INDICATIVE_ACTIVE_PRESENT         = INDICATIVE          #| PRESENT
INDICATIVE_ACTIVE_IMPERFECT       = INDICATIVE           | PAST   | ING
INDICATIVE_ACTIVE_FUTURE          = INDICATIVE           | FUTURE
INDICATIVE_ACTIVE_PERFECT         = INDICATIVE                    | PERFECT
INDICATIVE_ACTIVE_PAST_PERFECT    = INDICATIVE           | PAST   | PERFECT
INDICATIVE_ACTIVE_FUTURE_PERFECT  = INDICATIVE           | FUTURE | PERFECT
INDICATIVE_PASSIVE_PRESENT        = INDICATIVE | PASSIVE #| PRESENT
INDICATIVE_PASSIVE_IMPERFECT      = INDICATIVE | PASSIVE | PAST   | ING
INDICATIVE_PASSIVE_FUTURE         = INDICATIVE | PASSIVE | FUTURE
INDICATIVE_PASSIVE_PERFECT        = INDICATIVE | PASSIVE          | PERFECT
INDICATIVE_PASSIVE_PAST_PERFECT   = INDICATIVE | PASSIVE | PAST   | PERFECT
INDICATIVE_PASSIVE_FUTURE_PERFECT = INDICATIVE | PASSIVE | FUTURE | PERFECT

IMPERATIVE_ACTIVE_PRESENT         = IMPERATIVE           #| PRESENT
IMPERATIVE_ACTIVE_FUTURE          = IMPERATIVE           | FUTURE
IMPERATIVE_PASSIVE_PRESENT        = IMPERATIVE | PASSIVE #| PRESENT
IMPERATIVE_PASSIVE_FUTURE         = IMPERATIVE | PASSIVE | FUTURE

PARTICIPLE_PRESENT   = PARTICIPLE           #| PRESENT
# '+しつつある'
PARTICIPLE_FUTURE    = PARTICIPLE           | FUTURE
# '+しようとしている'
PARTICIPLE_PERFECT   = PARTICIPLE | PASSIVE          | PERFECT
# '+された'
